name: CI

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

      - name: Run tests
        run: uv run nox
